### ISSUE TITLE
Add file checks around loading the p11 and through good errors

### ISSUE THREAD

**Issue by rmhrisk** [microshine/pkcs11#1]
rmhrisk@peculiar-02:/tmp/pkcs11$ node test.js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'ref'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/tmp/pkcs11/lib/common.js:1:73)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by rmhrisk** [comment]
I miss understood it was complaining about the modules being missing closing
